.github/PULL_REQUEST_TEMPLATE.md, .gitignore
added pull request template and populated gitignore
=> Pull request template

views/main.handlebars
❗ Please **DO NOT** open a Pull Request without creating an Issue first. Failure to do so will result in the rejection of the pull request.
Insertion of basic html code in main.handlebars. Created various subfiles within views listing all handlebar pages that are currently planned.
Fixes #[issue]
N/A
Please provide an overview of code changes, especially key files and areas of significant change.
Demonstrate that the pull request is functional. For example: the exact commands to be run and their output; screenshots if the PR modifies the UI.
Self-explanatory.
=> Handlebar insertion

config/connection.js, models/User.js
Creates models folder, Users.js, config folder, connection.js
Fixes #31 #28 #25
=> Models folder

models/User.js, models/index.js
Fixes a typo on models/User.js and adds index.js to models/ to re-export models
=> Fixes type on User model definition. Adds index.js to models

models/Application.js
creates a basic application model to work with
Fixes #34
=> Application model

views/partials/interview-details.handlebars
Please provide a detailed explanation of the PR. What existing problem does it solve?
Fixes #39
Adds partial folder with starter code for interview modal
=> adds partials folder

.env.EXAMPLE, config/connection.js
Please provide a detailed explanation of the PR. What existing problem does it solve?
Fixes #[#33]
=> updated connection.js

controllers/api/index.js, controllers/api/userRoutes.js, controllers/index.js, models/Application.js, models/User.js, models/index.js
Fixes #57 
adds api folder to controllers folder, adds userRoutes.js and index.js to api folder.
creates post route in userRoutes to create new user
added module.exports = router to user and application models, updates models index to export application as well as user
=> 57 login/out

controllers/api/userRoutes.js, models/User.js
Fixes #69 #90
Adds user routes for login and logout, corrects create user route path. Adds bcrypt and a helper function to User model to check password for login.
=> 69/90 login/logout routes

public/css/styles.css, views/homepage.hbs, views/layouts/main.hbs, views/partials/interview-details.hbs
❗ Please **DO NOT** open a Pull Request without creating an Issue first. Failure to do so will result in the rejection of the pull request.
Design for homepage.hbs
Many codes in views file has been changed after running prettier. Homepage.hbs is also finished.
=> 98 css styling homepage

views/dashboard.hbs
Starts dashboard view layout
Fixes #70 #71 #72 
Additions to dashboard.handlebars, also adds a helpers folder
=> Starts dashboard view

public/css/styles.css, views/dashboard.hbs
Creates the structure of the application table on the dashboard view 
Fixes #73 
Changes to dashboard.handlebars file
=> Dashboard – Application Table

models/Application.js
Adds user_id to Application model to create a connection between users and their applications 
Fixes #111 
Changes made in Application.js file
=> adds user_id to the application model

seeds/index.js
makes bulk create await 
Fixes #113
=> added await to bulk creates

models/Application.js, models/Interview.js, models/index.js, seeds/index.js, seeds/interviewSeedData.json, views/partials/navbar.hbs
Adds seeding for Interview model
Fixes #65
=> Adds seeding for interviews table

config/connection.js, controllers/api/userRoutes.js, controllers/index.js, views/single-app.hbs
formatted hbs for single application view
Fixes #97
=> 97 single app handlebars - css-formatting

controllers/api/index.js, controllers/api/interviewRoutes.js, controllers/index.js
Adds interview routes and applications for the /dashboard routes
Fixes #68
=> Add interview api routes

controllers/api/applicationRoutes.js, controllers/api/index.js, views/dashboard.hbs
Please provide a detailed explanation of the PR. What existing problem does it solve?
Fixes #153
=> Dynamic Dashboard

controllers/api/applicationRoutes.js, controllers/index.js, helpers/helpers.js, public/js/application.js, server.js, views/application.hbs, views/single-app.hbs
=> Single app edit delete links

helpers/helpers.js, views/dashboard.hbs, views/single-app.hbs
updates single-app view to show badges for status and work site.
updates dashboard single application redirect to correct route
Fixes #92
=> status and work site badges on single app view

public/js/calendar.js, views/interviews.hbs
a lot of big brain code has been added where submiting information through clicking the submit button will add link references to the fullcalendar
=> 165 calendar seed input function

seeds/index.js
Creates an admin user with credentials admin@example.com and password admin123 for ease of use
=> Adds admin user to database while seeding

controllers/index.js, public/js/login.js
redirects to dashboard after login and after signup
Fixes #177
=> 177 app nav login nav

public/js/calendar.js
Changed calendar.js code where the videolink input is now being referenced directly to the respective website, not a route to the localhost.
=> seed input function rework

public/css/styles.css, public/js/calendar.js, seeds/index.js, views/homepage.hbs, views/interviews.hbs
Adds a more visually appealing gradient to the homepage
=> Gradient changes to homepage

public/js/calendar.js
=> local storage insertion

package.json, public/js/application.js, views/application.hbs, views/layouts/main.hbs, views/single-app.hbs
Adds Quill to include a rich text editor for the notes section of the application
Fixes #96  #91
=> 96 app notes format

README.md
Gave credit to my usage of Full Calendar global storage, and added node installation guidelines for future users to install this application.
=> README credits update/installation guide insertion
